name: glados-checkin

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # UTC时间 0点对应北京时间8点，7点对应北京时间15点
    - cron: '0 0,7 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 更新到最新的 checkout 版本
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 使用更简洁的版本规范
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Execute Checkin
        run: |
          python3 ./main.py
        env:
          SEND_SUBJECT: ${{ secrets.SEND_SUBJECT }}
          RECEIVE_ADDRESS: ${{ secrets.RECEIVE_ADDRESS }}
          SEND_BODY: ${{ secrets.SEND_BODY }}
          STMP_KEY: ${{ secrets.STMP_KEY }}
          SEND_ADDRESS: ${{ secrets.SEND_ADDRESS }}