name: Auto Send

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    # 北京时间 8 点、11 点、12 点、13 点、15 点 对应 UTC 时间 0 点、3 点、4 点、5 点、7 点
    - cron: '0 0,1,3,4,5,7 * * *'

jobs:
  email-checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 更新到最新的 checkout 版本
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 使用更简洁的版本规范
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute AutoSendEmail
        env:
          SEND_ADDRESS: ${{ secrets.SEND_ADDRESS }}
          SEND_SUBJECT: ${{ secrets.SEND_SUBJECT }}
          RECEIVE_ADDRESS: ${{ secrets.RECEIVE_ADDRESS }}
          SEND_BODY: ${{ secrets.SEND_BODY }}
          SMTP_KEY: ${{ secrets.SMTP_KEY }}
          AppID: ${{ secrets.AppID }}
          AppSecret: ${{ secrets.AppSecret }}
          OpenId: ${{ secrets.OpenId }}
          TemplateId: ${{ secrets.TemplateId }}
        run: python emailSend.py
      - name: Execute AutoSendWeChat
        env:
          SEND_ADDRESS: ${{ secrets.SEND_ADDRESS }}
          SEND_SUBJECT: ${{ secrets.SEND_SUBJECT }}
          RECEIVE_ADDRESS: ${{ secrets.RECEIVE_ADDRESS }}
          SEND_BODY: ${{ secrets.SEND_BODY }}
          SMTP_KEY: ${{ secrets.SMTP_KEY }}
          AppID: ${{ secrets.AppID }}
          AppSecret: ${{ secrets.AppSecret }}
          OpenId: ${{ secrets.OpenId }}
          TemplateId: ${{ secrets.TemplateId }}
        run: python wechatSend.py
        